version: '3'

services:

  app:
    build: .
    working_dir: /application/server
    env_file:
      - .env
    command: "tail -f /dev/null"
    # command: ["flask", "run", "--host=0.0.0.0", "--port=8001"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.10/site-packages
      - app-usr-local-bin:/usr/local/bin
      - ~/.ssh:/root/.ssh 
    ports:
      - "8001:8001"


volumes:
  app-python-site-packages:
    driver: local
  app-usr-local-bin:
    driver: local
