version: '3'

services:

  app:
    build: .
    working_dir: /application/server
    env_file:
      - .env
    command: "tail -f /dev/null"
    #     command: ["python", "manage.py", "runserver", "0:9001"]
    volumes:
      - .:/application
      - app-python-site-packages:/usr/local/lib/python3.8/site-packages
      - app-usr-local-bin:/usr/local/bin
      - ~/.ssh:/root/.ssh 
    ports:
      - "8000:8000"


volumes:
  app-python-site-packages:
    driver: local
  app-usr-local-bin:
    driver: local
